Feat Starter Kit
appwrite/starter-for-ios pull request #1
Opened 2024-12-19 06:50 UTC by ItzNotABug

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2024-12-19 10:39 UTC, loks0n requested changes

2024-12-19 10:39 UTC, loks0n commented on Sources/server/Appwrite.swift
> +    private let PUBLIC_APPWRITE_ENDPOINT = "https://cloud.appwrite.io/v1"
Can we put these in `Config.plist`?

2024-12-19 11:17 UTC, ItzNotABug commented on Sources/server/Appwrite.swift
> +    private let PUBLIC_APPWRITE_ENDPOINT = "https://cloud.appwrite.io/v1"
Done.

2025-02-24 14:36 UTC, ernstmul approved these changes

2025-02-25 15:09 UTC, merged